// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpoudvsozsiqxevgjsdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwb3VkdnNvenNpcXhldmdqc2RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjA4MjMsImV4cCI6MjA1OTA5NjgyM30.EH8K5k_mnAS142EpEutCZnB1TrGZcha0cYlBs3h7Ses";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);